spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/simpleGame?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: admin123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  devtools:
    restart:
      enabled: false


jwt:
  key: eyJzdWIiOiJzaW1wbGVHYW1lIiwibmFtZSI6ImppaHVuIiwiaWF0IjoxNTE2MjM5MDIyfQ


#  [??]
#- ???? ??
#  docker run --name jihun-mysql -e MYSQL_ROOT_PASSWORD=yourpassword -p 3307:3306 -d mysql:latest
#- MySql DB ??
#  docker exec -it simpleGame bash
#  mysql -u root -p
#  CREATE DATABASE simpleGame;